---
title: "Reporte - Análisis Melanoma vs. Ketosis Seborreica"
author: "Equipo CT"
date: "17/03/2023"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")

```

## Melanoma vs Seborreic_Keratosis


```{r functions,echo = FALSE }

library("FRESA.CAD")
library("e1071")
library("fastAdaboost")
library("readxl")

```


## Loading data sets

```{r FRESA Map, results = "hide", dpi=300, fig.height= 6.0, fig.width= 8.0}
op <- par(no.readonly = TRUE)

MelanomaFeatures <- read.csv("/Users/juanluis/Downloads/LearningMelanoma/MelanomaLesionFeatures.csv", header=FALSE)
SeborrheicFeatures <- read.csv("/Users/juanluis/Downloads/LearningMelanoma/SeborrheicLesionFeatures.csv", header=FALSE)
MelanomaControlFeatures <- read.csv("/Users/juanluis/Downloads/LearningMelanoma/MelanomaControlFeatures.csv", header=FALSE)
SeborrheicControlFeatures <- read.csv("/Users/juanluis/Downloads/LearningMelanoma/SeborrheicControlFeatures.csv", header=FALSE)
LesionFeatureNames <- read_excel("/Users/juanluis/Downloads/LearningMelanoma/FeatureNames.xlsx")
ControlFeatureNames <- read_excel("/Users/juanluis/Downloads/LearningMelanoma/FeatureNames.xlsx",sheet = "Control")
FeatureNames <- read_excel("/Users/juanluis/Downloads/LearningMelanoma/FeatureNames.xlsx",sheet = "PerChannel")

colnames(MelanomaFeatures) <- LesionFeatureNames$FinalName
colnames(SeborrheicFeatures) <- LesionFeatureNames$FinalName
colnames(MelanomaControlFeatures) <- ControlFeatureNames$FinalName
colnames(SeborrheicControlFeatures) <- ControlFeatureNames$FinalName


sum(is.na(MelanomaFeatures))
sum(is.na(SeborrheicFeatures))
sum(is.na(MelanomaControlFeatures))

channel1 <- c(1:32)
channel2 <- c(33:64)
channel3 <- c(65:96)

MMelanomaFeatures <- (  MelanomaFeatures[,channel1] +
                        MelanomaFeatures[,channel2] +
                        MelanomaFeatures[,channel3] )/3.0
SMelanomaFeatures <- (  abs(MelanomaFeatures[,channel1] - MMelanomaFeatures) +
                        abs(MelanomaFeatures[,channel2] - MMelanomaFeatures) +
                        abs(MelanomaFeatures[,channel3] - MMelanomaFeatures) )/3.0

colnames(MMelanomaFeatures) <- paste("M",FeatureNames$Features,sep="")
colnames(SMelanomaFeatures) <- paste("S",FeatureNames$Features,sep="")

MelanomaFeatures <- cbind(MelanomaFeatures,SMelanomaFeatures/(0.01+abs(MMelanomaFeatures)))


MSeborrheicFeatures <- (  SeborrheicFeatures[,channel1] +
                          SeborrheicFeatures[,channel2] +
                          SeborrheicFeatures[,channel3] )/3.0
SSeborrheicFeatures <- (abs(SeborrheicFeatures[,channel1] - MSeborrheicFeatures) +
                        abs(SeborrheicFeatures[,channel2] - MSeborrheicFeatures) +
                        abs(SeborrheicFeatures[,channel3] - MSeborrheicFeatures))/3.0
colnames(MSeborrheicFeatures) <- paste("M",FeatureNames$Features,sep="")
colnames(SSeborrheicFeatures) <- paste("S",FeatureNames$Features,sep="")

SeborrheicFeatures <- cbind(SeborrheicFeatures,SSeborrheicFeatures/(0.001+abs(MSeborrheicFeatures)))

MMelanomaControlFeatures <- (  MelanomaControlFeatures[,channel1] +
                               MelanomaControlFeatures[,channel2] +
                               MelanomaControlFeatures[,channel3] )/3.0

SMelanomaControlFeatures <- (abs(MelanomaControlFeatures[,channel1] - MMelanomaControlFeatures) +
                             abs(MelanomaControlFeatures[,channel2] - MMelanomaControlFeatures) +
                             abs(MelanomaControlFeatures[,channel3] - MMelanomaControlFeatures))/3.0
colnames(MMelanomaControlFeatures) <- paste("M_C",FeatureNames$Features,sep="")
colnames(SMelanomaControlFeatures) <- paste("S_C",FeatureNames$Features,sep="")


MelanomaControlFeatures <- cbind(MelanomaControlFeatures,SMelanomaControlFeatures/(0.001+abs(MMelanomaControlFeatures)))


MSeborrheicControlFeatures <- (  SeborrheicControlFeatures[,channel1] +
                                 SeborrheicControlFeatures[,channel2] +
                                 SeborrheicControlFeatures[,channel3] )/3.0
SSeborrheicControlFeatures <- (abs(SeborrheicControlFeatures[,channel1] - MSeborrheicControlFeatures) +
                               abs(SeborrheicControlFeatures[,channel2] - MSeborrheicControlFeatures) +
                               abs(SeborrheicControlFeatures[,channel3] - MSeborrheicControlFeatures))/3.0

               trainFraction = 0.90,
               repetitions = 100,
               classSamplingType = "Pro",
               featureSelectionFunction = univariate_KS,
               featureSelection.control = list(pvalue=0.05,limit= -1),
               kn=5
               )

```

## Plot performance

```{r, dpi=300, fig.height= 6.0, fig.width= 8.0}
performace <- predictionStats_binary(cvKNN$medianTest,"KNN")
par(op)

```

## Learning Melanoma with KNN

```{r}
cvKNN <- randomCV(MelanomaSeborrheic,"Class",
               KNN_method,
               trainFraction = 0.90,
               repetitions = 100,
               classSamplingType = "Pro",
               featureSelectionFunction = univariate_KS,
               featureSelection.control = list(pvalue=0.05,limit= -1),
               kn=10
               )

```

## Plot performance

```{r, dpi=300, fig.height= 6.0, fig.width= 8.0}
performace <- predictionStats_binary(cvKNN$medianTest,"KNN")
par(op)

```
## A01383088 Juan Luis Flores Sánchez
## Azul Sofía Moctezuma Enriquez A01562585
